version: "3.8"

services:
  app:
    build:
      context: .
    volumes:
        - .:/core
    ports:
      - "8080:8080"
    image: app:react
    container_name: pokemon_viewer_container
    command:  npm start